// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Whyvra.Tunnel.Data;

namespace Whyvra.Tunnel.Data.Sqlite.Migrations
{
    [DbContext(typeof(TunnelContext))]
    [Migration("20201025214849_InitialConfig")]
    partial class InitialConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entitites.ClientNetworkAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NetworkAddressId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("NetworkAddressId", "ClientId")
                        .IsUnique();

                    b.ToTable("ClientNetworkAddresses");
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entitites.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(16);

                    b.Property<int>("RecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(45);

                    b.Property<string>("TableId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(32);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entitites.NetworkAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("NetworkAddresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "0.0.0.0/0",
                            CreatedAt = new DateTime(2020, 10, 25, 21, 48, 49, 146, DateTimeKind.Utc).AddTicks(9157),
                            UpdatedAt = new DateTime(2020, 10, 25, 21, 48, 49, 146, DateTimeKind.Utc).AddTicks(9157)
                        },
                        new
                        {
                            Id = 2,
                            Address = "::/0",
                            CreatedAt = new DateTime(2020, 10, 25, 21, 48, 49, 146, DateTimeKind.Utc).AddTicks(9157),
                            UpdatedAt = new DateTime(2020, 10, 25, 21, 48, 49, 146, DateTimeKind.Utc).AddTicks(9157)
                        });
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entitites.ServerNetworkAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NetworkAddressId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("NetworkAddressId", "ServerId")
                        .IsUnique();

                    b.ToTable("ServerNetworkAddresses");
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entitites.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<Guid>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 10, 25, 21, 48, 49, 152, DateTimeKind.Utc).AddTicks(6369),
                            Email = "system@example.com",
                            FirstName = "System",
                            LastName = "User",
                            Uid = new Guid("e3adf55b-7430-42c1-ae62-758d7b644fdb"),
                            UpdatedAt = new DateTime(2020, 10, 25, 21, 48, 49, 152, DateTimeKind.Utc).AddTicks(6369),
                            Username = "system_user"
                        });
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entitites.WireguardClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<bool>("IsRevoked")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(44);

                    b.Property<int>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedIp")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ServerId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entitites.WireguardServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("Dns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(44);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entitites.ClientNetworkAddress", b =>
                {
                    b.HasOne("Whyvra.Tunnel.Domain.Entitites.WireguardClient", "Client")
                        .WithMany("AllowedIps")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whyvra.Tunnel.Domain.Entitites.NetworkAddress", "NetworkAddress")
                        .WithMany()
                        .HasForeignKey("NetworkAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entitites.Event", b =>
                {
                    b.HasOne("Whyvra.Tunnel.Domain.Entitites.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entitites.ServerNetworkAddress", b =>
                {
                    b.HasOne("Whyvra.Tunnel.Domain.Entitites.NetworkAddress", "NetworkAddress")
                        .WithMany()
                        .HasForeignKey("NetworkAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whyvra.Tunnel.Domain.Entitites.WireguardServer", "Server")
                        .WithMany("DefaultAllowedRange")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entitites.WireguardClient", b =>
                {
                    b.HasOne("Whyvra.Tunnel.Domain.Entitites.WireguardServer", "Server")
                        .WithMany("Clients")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
