// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Whyvra.Tunnel.Data;

#nullable disable

namespace Whyvra.Tunnel.Data.Sqlite.Migrations
{
    [DbContext(typeof(TunnelContext))]
    [Migration("20220520175551_AddNewServerColumns")]
    partial class AddNewServerColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("AssignedIp", "ServerId")
                        .IsUnique();

                    b.HasIndex("Name", "ServerId")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entities.ClientNetworkAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NetworkAddressId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("NetworkAddressId", "ClientId")
                        .IsUnique();

                    b.ToTable("ClientNetworkAddresses");
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entities.NetworkAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("NetworkAddresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "0.0.0.0/0",
                            CreatedAt = new DateTime(2020, 10, 25, 21, 48, 49, 146, DateTimeKind.Utc).AddTicks(9157),
                            UpdatedAt = new DateTime(2020, 10, 25, 21, 48, 49, 146, DateTimeKind.Utc).AddTicks(9157)
                        },
                        new
                        {
                            Id = 2,
                            Address = "::/0",
                            CreatedAt = new DateTime(2020, 10, 25, 21, 48, 49, 146, DateTimeKind.Utc).AddTicks(9157),
                            UpdatedAt = new DateTime(2020, 10, 25, 21, 48, 49, 146, DateTimeKind.Utc).AddTicks(9157)
                        });
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entities.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<bool?>("AddFirewallRules")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnOrder(11);

                    b.Property<string>("AssignedRange")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(15);

                    b.Property<string>("CustomConfiguration")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(13);

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<string>("Dns")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<int>("ListenPort")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(7);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("NetworkInterface")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("eth0")
                        .HasColumnOrder(12);

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<bool>("RenderToDisk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnOrder(10);

                    b.Property<string>("StatusApi")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(16);

                    b.Property<string>("WireGuardInterface")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(14);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("WireGuardInterface")
                        .IsUnique();

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entities.ServerNetworkAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NetworkAddressId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("NetworkAddressId", "ServerId")
                        .IsUnique();

                    b.ToTable("ServerNetworkAddresses");
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 10, 25, 21, 48, 49, 152, DateTimeKind.Utc).AddTicks(6369),
                            Email = "system@example.com",
                            FirstName = "System",
                            LastName = "User",
                            Uid = new Guid("e3adf55b-7430-42c1-ae62-758d7b644fdb"),
                            UpdatedAt = new DateTime(2020, 10, 25, 21, 48, 49, 152, DateTimeKind.Utc).AddTicks(6369),
                            Username = "system_user"
                        });
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entities.Client", b =>
                {
                    b.HasOne("Whyvra.Tunnel.Domain.Entities.Server", "Server")
                        .WithMany("Clients")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entities.ClientNetworkAddress", b =>
                {
                    b.HasOne("Whyvra.Tunnel.Domain.Entities.Client", "Client")
                        .WithMany("AllowedIps")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whyvra.Tunnel.Domain.Entities.NetworkAddress", "NetworkAddress")
                        .WithMany()
                        .HasForeignKey("NetworkAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("NetworkAddress");
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entities.Event", b =>
                {
                    b.HasOne("Whyvra.Tunnel.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entities.ServerNetworkAddress", b =>
                {
                    b.HasOne("Whyvra.Tunnel.Domain.Entities.NetworkAddress", "NetworkAddress")
                        .WithMany()
                        .HasForeignKey("NetworkAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whyvra.Tunnel.Domain.Entities.Server", "Server")
                        .WithMany("DefaultAllowedRange")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NetworkAddress");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entities.Client", b =>
                {
                    b.Navigation("AllowedIps");
                });

            modelBuilder.Entity("Whyvra.Tunnel.Domain.Entities.Server", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("DefaultAllowedRange");
                });
#pragma warning restore 612, 618
        }
    }
}
