name: Tunnel

# Triggers the workflow when pushing to master
on:
  push:
    branches:
      - master

jobs:
  build-code:
    environment: Docker Hub
    runs-on: ubuntu-18.04
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install versioning tool
        run: dotnet tool install --global Whyvra.GitV

      - name: Calculate version
        run: |
          echo "AssemblyVersion=$(gitv -a)" >> $GITHUB_ENV
          echo "ModuleVersion=$(gitv)" >> $GITHUB_ENV
          echo "MajorMinVersion=$(gitv | cut -f1,2 -d '.')" >> $GITHUB_ENV

      - name: Copy Blazor settings
        run: cp ./docker/blazor.appsettings.json ./Whyvra.Tunnel.Presentation/wwwroot/appsettings.json

      - name: Build code
        run: |
          dotnet restore
          dotnet publish Whyvra.Tunnel.Api -c Release -o Build/api -f net5.0 --self-contained false --no-restore -p:Version=$AssemblyVersion
          dotnet publish Whyvra.Tunnel.Presentation -c Release -o Build --no-restore -p:Version=$AssemblyVersion

      - name: Cleanup compressed Blazor appsettings
        run: rm ./Build/wwwroot/appsettings.json.*

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            whyvra/tunnel:latest
            whyvra/tunnel:${{ env.ModuleVersion }}
            whyvra/tunnel:${{ env.MajorMinVersion }}
